version: '3.8'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: ${USERPOSTGRES}
      POSTGRES_PASSWORD: ${PASSWORDPOSTGRES}
      POSTGRES_DB: ${DBNAME}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      USERPOSTGRES: ${USERPOSTGRES}
      POSTGRESDRIVER: ${POSTGRESDRIVER}
      HOSTPOSTGRES: ${HOSTPOSTGRES}
      PORTPOSTGRES: ${PORTPOSTGRES}
      PASSWORDPOSTGRES: ${PASSWORDPOSTGRES}
      DBNAME: ${DBNAME}
    depends_on:
      - postgres
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
