# fly.toml app configuration file generated for lacos-v2 on 2024-11-20T12:18:06Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'lacos-v2'
primary_region = 'gig'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
