app = "lacos-v2"
primary_region = "gig"

[build]
dockerfile = "Dockerfile"

[http_service]
auto_start_machines = true
auto_stop_machines = true
force_https = true
internal_port = 8080
min_machines_running = 0
processes = ["app"]

[[vm]]
size = "shared-cpu-1x"

[[services]]
  internal_port = 5432
  protocol = "tcp"
  postgresql = true 
